// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: account_balance.sql

package sqlc

import (
	"github.com/google/uuid"
)

type CreateAccountBalancesParams struct {
	Amount    int64     `json:"amount"`
	AccountID uuid.UUID `json:"account_id"`
}
