// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForCreateManyInstitutions implements pgx.CopyFromSource.
type iteratorForCreateManyInstitutions struct {
	rows                 []CreateManyInstitutionsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateManyInstitutions) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateManyInstitutions) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ExternalID,
		r.rows[0].Name,
		r.rows[0].Logo,
	}, nil
}

func (r iteratorForCreateManyInstitutions) Err() error {
	return nil
}

func (q *Queries) CreateManyInstitutions(ctx context.Context, arg []CreateManyInstitutionsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"institutions"}, []string{"external_id", "name", "logo"}, &iteratorForCreateManyInstitutions{rows: arg})
}
