// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: feedback.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createFeedback = `-- name: CreateFeedback :exec
INSERT INTO feedbacks (message, user_id)
VALUES ($1, $2)
`

type CreateFeedbackParams struct {
	Message string     `json:"message"`
	UserID  *uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateFeedback(ctx context.Context, arg CreateFeedbackParams) error {
	_, err := q.db.Exec(ctx, createFeedback, arg.Message, arg.UserID)
	return err
}
