// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID            uuid.UUID  `json:"id"`
	ExternalID    string     `json:"external_id"`
	Name          string     `json:"name"`
	Type          string     `json:"type"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
	DeletedAt     *time.Time `json:"deleted_at"`
	UserID        uuid.UUID  `json:"user_id"`
	InstitutionID uuid.UUID  `json:"institution_id"`
}

type Budget struct {
	ID        uuid.UUID  `json:"id"`
	Amount    int64      `json:"amount"`
	Date      time.Time  `json:"date"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
	UserID    uuid.UUID  `json:"user_id"`
}

type BudgetCategory struct {
	ID         uuid.UUID  `json:"id"`
	Amount     int64      `json:"amount"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
	DeletedAt  *time.Time `json:"deleted_at"`
	BudgetID   uuid.UUID  `json:"budget_id"`
	CategoryID uuid.UUID  `json:"category_id"`
}

type Category struct {
	ID         uuid.UUID  `json:"id"`
	ExternalID string     `json:"external_id"`
	Name       string     `json:"name"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
	DeletedAt  *time.Time `json:"deleted_at"`
}

type Institution struct {
	ID         uuid.UUID   `json:"id"`
	ExternalID string      `json:"external_id"`
	Name       string      `json:"name"`
	Logo       pgtype.Text `json:"logo"`
	CreatedAt  time.Time   `json:"created_at"`
	UpdatedAt  time.Time   `json:"updated_at"`
	DeletedAt  *time.Time  `json:"deleted_at"`
}

type Investment struct {
	ID         uuid.UUID  `json:"id"`
	ExternalID string     `json:"external_id"`
	Name       string     `json:"name"`
	Amount     int64      `json:"amount"`
	Type       string     `json:"type"`
	Rate       float64    `json:"rate"`
	RateType   string     `json:"rateType"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
	DeletedAt  *time.Time `json:"deleted_at"`
	UserID     uuid.UUID  `json:"user_id"`
}

type PaymentMethod struct {
	ID         uuid.UUID  `json:"id"`
	ExternalID string     `json:"external_id"`
	Name       string     `json:"name"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
	DeletedAt  *time.Time `json:"deleted_at"`
}

type Transaction struct {
	ID              uuid.UUID  `json:"id"`
	ExternalID      string     `json:"external_id"`
	Name            string     `json:"name"`
	Amount          int64      `json:"amount"`
	IsIgnored       bool       `json:"is_ignored"`
	Date            time.Time  `json:"date"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
	DeletedAt       *time.Time `json:"deleted_at"`
	PaymentMethodID uuid.UUID  `json:"payment_method_id"`
	UserID          uuid.UUID  `json:"user_id"`
	AccountID       *uuid.UUID `json:"account_id"`
	InstitutionID   *uuid.UUID `json:"institution_id"`
	CategoryID      *uuid.UUID `json:"category_id"`
}

type User struct {
	ID                    uuid.UUID   `json:"id"`
	ExternalID            string      `json:"external_id"`
	Provider              string      `json:"provider"`
	Name                  string      `json:"name"`
	Email                 string      `json:"email"`
	VerifiedEmail         bool        `json:"verified_email"`
	Tier                  string      `json:"tier"`
	Avatar                pgtype.Text `json:"avatar"`
	SubscriptionExpiresAt *time.Time  `json:"subscription_expires_at"`
	SynchronizedAt        *time.Time  `json:"synchronized_at"`
	CreatedAt             time.Time   `json:"created_at"`
	UpdatedAt             time.Time   `json:"updated_at"`
	DeletedAt             *time.Time  `json:"deleted_at"`
}
