// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID            uuid.UUID  `json:"id"`
	ExternalID    string     `json:"external_id"`
	Name          string     `json:"name"`
	Type          string     `json:"type"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
	DeletedAt     *time.Time `json:"deleted_at"`
	UserID        uuid.UUID  `json:"user_id"`
	InstitutionID uuid.UUID  `json:"institution_id"`
}

type AccountBalance struct {
	ID        uuid.UUID  `json:"id"`
	Amount    int64      `json:"amount"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
	AccountID uuid.UUID  `json:"account_id"`
	UserID    uuid.UUID  `json:"user_id"`
}

type AiChat struct {
	ID        uuid.UUID  `json:"id"`
	Title     *string    `json:"title"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
	UserID    uuid.UUID  `json:"user_id"`
}

type AiChatMessage struct {
	ID              uuid.UUID  `json:"id"`
	Message         string     `json:"message"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
	DeletedAt       *time.Time `json:"deleted_at"`
	CreatedByUserID *uuid.UUID `json:"created_by_user_id"`
	AiChatID        uuid.UUID  `json:"ai_chat_id"`
}

type Budget struct {
	ID        uuid.UUID  `json:"id"`
	Amount    int64      `json:"amount"`
	Date      time.Time  `json:"date"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
	UserID    uuid.UUID  `json:"user_id"`
}

type BudgetCategory struct {
	ID         uuid.UUID  `json:"id"`
	Amount     int64      `json:"amount"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
	DeletedAt  *time.Time `json:"deleted_at"`
	BudgetID   uuid.UUID  `json:"budget_id"`
	CategoryID uuid.UUID  `json:"category_id"`
}

type Feedback struct {
	ID        uuid.UUID  `json:"id"`
	Message   string     `json:"message"`
	CreatedAt time.Time  `json:"created_at"`
	DeletedAt *time.Time `json:"deleted_at"`
	UserID    *uuid.UUID `json:"user_id"`
}

type Institution struct {
	ID         uuid.UUID  `json:"id"`
	ExternalID string     `json:"external_id"`
	Name       string     `json:"name"`
	Logo       *string    `json:"logo"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
	DeletedAt  *time.Time `json:"deleted_at"`
}

type Investment struct {
	ID         uuid.UUID  `json:"id"`
	ExternalID string     `json:"external_id"`
	Name       string     `json:"name"`
	Amount     int64      `json:"amount"`
	Rate       int64      `json:"rate"`
	RateType   string     `json:"rateType"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
	DeletedAt  *time.Time `json:"deleted_at"`
	CategoryID uuid.UUID  `json:"category_id"`
	UserID     uuid.UUID  `json:"user_id"`
}

type InvestmentCategory struct {
	ID         uuid.UUID  `json:"id"`
	ExternalID string     `json:"external_id"`
	Name       string     `json:"name"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
	DeletedAt  *time.Time `json:"deleted_at"`
}

type PaymentMethod struct {
	ID         uuid.UUID  `json:"id"`
	ExternalID string     `json:"external_id"`
	Name       string     `json:"name"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
	DeletedAt  *time.Time `json:"deleted_at"`
}

type Transaction struct {
	ID              uuid.UUID  `json:"id"`
	ExternalID      *string    `json:"external_id"`
	Name            string     `json:"name"`
	Amount          int64      `json:"amount"`
	IsIgnored       bool       `json:"is_ignored"`
	Date            time.Time  `json:"date"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
	DeletedAt       *time.Time `json:"deleted_at"`
	PaymentMethodID uuid.UUID  `json:"payment_method_id"`
	UserID          uuid.UUID  `json:"user_id"`
	AccountID       *uuid.UUID `json:"account_id"`
	InstitutionID   *uuid.UUID `json:"institution_id"`
	CategoryID      *uuid.UUID `json:"category_id"`
}

type TransactionCategory struct {
	ID         uuid.UUID  `json:"id"`
	ExternalID string     `json:"external_id"`
	Name       string     `json:"name"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
	DeletedAt  *time.Time `json:"deleted_at"`
}

type User struct {
	ID                    uuid.UUID  `json:"id"`
	Provider              string     `json:"provider"`
	Name                  string     `json:"name"`
	Email                 string     `json:"email"`
	VerifiedEmail         bool       `json:"verified_email"`
	Tier                  string     `json:"tier"`
	Avatar                *string    `json:"avatar"`
	SubscriptionExpiresAt *time.Time `json:"subscription_expires_at"`
	SynchronizedAt        *time.Time `json:"synchronized_at"`
	CreatedAt             time.Time  `json:"created_at"`
	UpdatedAt             time.Time  `json:"updated_at"`
	DeletedAt             *time.Time `json:"deleted_at"`
	AuthID                string     `json:"auth_id"`
	OpenFinanceID         *string    `json:"open_finance_id"`
}
