// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: payment_method.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type CreatePaymentMethodsParams struct {
	ExternalID string `json:"external_id"`
	Name       string `json:"name"`
}

const getPaymentMethodByID = `-- name: GetPaymentMethodByID :one
SELECT id, external_id, name, search_document, created_at, deleted_at
FROM payment_methods
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetPaymentMethodByID(ctx context.Context, id uuid.UUID) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, getPaymentMethodByID, id)
	var i PaymentMethod
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Name,
		&i.SearchDocument,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
