// Code generated by prisma-go-tools. DO NOT EDIT.

package schema

import "fmt"

type tableAIChat string

func (t tableAIChat) Table() string {
	return string(t)
}

func (t tableAIChat) ColumnAll() string {
	return fmt.Sprintf("%s.*", t)
}

func (t tableAIChat) ColumnUpdatedAt() string {
	return fmt.Sprintf("%s.updated_at", t)
}

func (t tableAIChat) ColumnDeletedAt() string {
	return fmt.Sprintf("%s.deleted_at", t)
}

func (t tableAIChat) ColumnUserID() string {
	return fmt.Sprintf("%s.user_id", t)
}

func (t tableAIChat) ColumnID() string {
	return fmt.Sprintf("%s.id", t)
}

func (t tableAIChat) ColumnTitle() string {
	return fmt.Sprintf("%s.title", t)
}

func (t tableAIChat) ColumnCreatedAt() string {
	return fmt.Sprintf("%s.created_at", t)
}

const AIChat = tableAIChat("ai_chats")

type tableAIChatAnswer string

func (t tableAIChatAnswer) Table() string {
	return string(t)
}

func (t tableAIChatAnswer) ColumnAll() string {
	return fmt.Sprintf("%s.*", t)
}

func (t tableAIChatAnswer) ColumnUpdatedAt() string {
	return fmt.Sprintf("%s.updated_at", t)
}

func (t tableAIChatAnswer) ColumnDeletedAt() string {
	return fmt.Sprintf("%s.deleted_at", t)
}

func (t tableAIChatAnswer) ColumnAiChatMessageID() string {
	return fmt.Sprintf("%s.ai_chat_message_id", t)
}

func (t tableAIChatAnswer) ColumnID() string {
	return fmt.Sprintf("%s.id", t)
}

func (t tableAIChatAnswer) ColumnMessage() string {
	return fmt.Sprintf("%s.message", t)
}

func (t tableAIChatAnswer) ColumnRating() string {
	return fmt.Sprintf("%s.rating", t)
}

func (t tableAIChatAnswer) ColumnCreatedAt() string {
	return fmt.Sprintf("%s.created_at", t)
}

const AIChatAnswer = tableAIChatAnswer("ai_chat_answers")

type tableAIChatMessage string

func (t tableAIChatMessage) Table() string {
	return string(t)
}

func (t tableAIChatMessage) ColumnAll() string {
	return fmt.Sprintf("%s.*", t)
}

func (t tableAIChatMessage) ColumnMessage() string {
	return fmt.Sprintf("%s.message", t)
}

func (t tableAIChatMessage) ColumnCreatedAt() string {
	return fmt.Sprintf("%s.created_at", t)
}

func (t tableAIChatMessage) ColumnDeletedAt() string {
	return fmt.Sprintf("%s.deleted_at", t)
}

func (t tableAIChatMessage) ColumnAiChatID() string {
	return fmt.Sprintf("%s.ai_chat_id", t)
}

func (t tableAIChatMessage) ColumnID() string {
	return fmt.Sprintf("%s.id", t)
}

const AIChatMessage = tableAIChatMessage("ai_chat_messages")

type tableAccount string

func (t tableAccount) Table() string {
	return string(t)
}

func (t tableAccount) ColumnAll() string {
	return fmt.Sprintf("%s.*", t)
}

func (t tableAccount) ColumnDeletedAt() string {
	return fmt.Sprintf("%s.deleted_at", t)
}

func (t tableAccount) ColumnUserInstitutionID() string {
	return fmt.Sprintf("%s.user_institution_id", t)
}

func (t tableAccount) ColumnID() string {
	return fmt.Sprintf("%s.id", t)
}

func (t tableAccount) ColumnExternalID() string {
	return fmt.Sprintf("%s.external_id", t)
}

func (t tableAccount) ColumnName() string {
	return fmt.Sprintf("%s.name", t)
}

func (t tableAccount) ColumnType() string {
	return fmt.Sprintf("%s.type", t)
}

func (t tableAccount) ColumnCreatedAt() string {
	return fmt.Sprintf("%s.created_at", t)
}

const Account = tableAccount("accounts")

type tableAccountBalance string

func (t tableAccountBalance) Table() string {
	return string(t)
}

func (t tableAccountBalance) ColumnAll() string {
	return fmt.Sprintf("%s.*", t)
}

func (t tableAccountBalance) ColumnDeletedAt() string {
	return fmt.Sprintf("%s.deleted_at", t)
}

func (t tableAccountBalance) ColumnAccountID() string {
	return fmt.Sprintf("%s.account_id", t)
}

func (t tableAccountBalance) ColumnID() string {
	return fmt.Sprintf("%s.id", t)
}

func (t tableAccountBalance) ColumnAmount() string {
	return fmt.Sprintf("%s.amount", t)
}

func (t tableAccountBalance) ColumnCreatedAt() string {
	return fmt.Sprintf("%s.created_at", t)
}

const AccountBalance = tableAccountBalance("account_balances")

type tableBudget string

func (t tableBudget) Table() string {
	return string(t)
}

func (t tableBudget) ColumnAll() string {
	return fmt.Sprintf("%s.*", t)
}

func (t tableBudget) ColumnDeletedAt() string {
	return fmt.Sprintf("%s.deleted_at", t)
}

func (t tableBudget) ColumnUserID() string {
	return fmt.Sprintf("%s.user_id", t)
}

func (t tableBudget) ColumnID() string {
	return fmt.Sprintf("%s.id", t)
}

func (t tableBudget) ColumnAmount() string {
	return fmt.Sprintf("%s.amount", t)
}

func (t tableBudget) ColumnDate() string {
	return fmt.Sprintf("%s.date", t)
}

func (t tableBudget) ColumnCreatedAt() string {
	return fmt.Sprintf("%s.created_at", t)
}

func (t tableBudget) ColumnUpdatedAt() string {
	return fmt.Sprintf("%s.updated_at", t)
}

const Budget = tableBudget("budgets")

type tableBudgetCategory string

func (t tableBudgetCategory) Table() string {
	return string(t)
}

func (t tableBudgetCategory) ColumnAll() string {
	return fmt.Sprintf("%s.*", t)
}

func (t tableBudgetCategory) ColumnID() string {
	return fmt.Sprintf("%s.id", t)
}

func (t tableBudgetCategory) ColumnAmount() string {
	return fmt.Sprintf("%s.amount", t)
}

func (t tableBudgetCategory) ColumnCreatedAt() string {
	return fmt.Sprintf("%s.created_at", t)
}

func (t tableBudgetCategory) ColumnUpdatedAt() string {
	return fmt.Sprintf("%s.updated_at", t)
}

func (t tableBudgetCategory) ColumnDeletedAt() string {
	return fmt.Sprintf("%s.deleted_at", t)
}

func (t tableBudgetCategory) ColumnBudgetID() string {
	return fmt.Sprintf("%s.budget_id", t)
}

func (t tableBudgetCategory) ColumnCategoryID() string {
	return fmt.Sprintf("%s.category_id", t)
}

const BudgetCategory = tableBudgetCategory("budget_categories")

type tableFeedback string

func (t tableFeedback) Table() string {
	return string(t)
}

func (t tableFeedback) ColumnAll() string {
	return fmt.Sprintf("%s.*", t)
}

func (t tableFeedback) ColumnDeletedAt() string {
	return fmt.Sprintf("%s.deleted_at", t)
}

func (t tableFeedback) ColumnUserID() string {
	return fmt.Sprintf("%s.user_id", t)
}

func (t tableFeedback) ColumnID() string {
	return fmt.Sprintf("%s.id", t)
}

func (t tableFeedback) ColumnMessage() string {
	return fmt.Sprintf("%s.message", t)
}

func (t tableFeedback) ColumnCreatedAt() string {
	return fmt.Sprintf("%s.created_at", t)
}

const Feedback = tableFeedback("feedbacks")

type tableInstitution string

func (t tableInstitution) Table() string {
	return string(t)
}

func (t tableInstitution) ColumnAll() string {
	return fmt.Sprintf("%s.*", t)
}

func (t tableInstitution) ColumnName() string {
	return fmt.Sprintf("%s.name", t)
}

func (t tableInstitution) ColumnLogo() string {
	return fmt.Sprintf("%s.logo", t)
}

func (t tableInstitution) ColumnCreatedAt() string {
	return fmt.Sprintf("%s.created_at", t)
}

func (t tableInstitution) ColumnDeletedAt() string {
	return fmt.Sprintf("%s.deleted_at", t)
}

func (t tableInstitution) ColumnID() string {
	return fmt.Sprintf("%s.id", t)
}

func (t tableInstitution) ColumnExternalID() string {
	return fmt.Sprintf("%s.external_id", t)
}

const Institution = tableInstitution("institutions")

type tablePaymentMethod string

func (t tablePaymentMethod) Table() string {
	return string(t)
}

func (t tablePaymentMethod) ColumnAll() string {
	return fmt.Sprintf("%s.*", t)
}

func (t tablePaymentMethod) ColumnID() string {
	return fmt.Sprintf("%s.id", t)
}

func (t tablePaymentMethod) ColumnExternalID() string {
	return fmt.Sprintf("%s.external_id", t)
}

func (t tablePaymentMethod) ColumnName() string {
	return fmt.Sprintf("%s.name", t)
}

func (t tablePaymentMethod) ColumnCreatedAt() string {
	return fmt.Sprintf("%s.created_at", t)
}

func (t tablePaymentMethod) ColumnDeletedAt() string {
	return fmt.Sprintf("%s.deleted_at", t)
}

const PaymentMethod = tablePaymentMethod("payment_methods")

type tableTransaction string

func (t tableTransaction) Table() string {
	return string(t)
}

func (t tableTransaction) ColumnAll() string {
	return fmt.Sprintf("%s.*", t)
}

func (t tableTransaction) ColumnID() string {
	return fmt.Sprintf("%s.id", t)
}

func (t tableTransaction) ColumnExternalID() string {
	return fmt.Sprintf("%s.external_id", t)
}

func (t tableTransaction) ColumnName() string {
	return fmt.Sprintf("%s.name", t)
}

func (t tableTransaction) ColumnDate() string {
	return fmt.Sprintf("%s.date", t)
}

func (t tableTransaction) ColumnPaymentMethodID() string {
	return fmt.Sprintf("%s.payment_method_id", t)
}

func (t tableTransaction) ColumnUserID() string {
	return fmt.Sprintf("%s.user_id", t)
}

func (t tableTransaction) ColumnCategoryID() string {
	return fmt.Sprintf("%s.category_id", t)
}

func (t tableTransaction) ColumnAccountID() string {
	return fmt.Sprintf("%s.account_id", t)
}

func (t tableTransaction) ColumnAmount() string {
	return fmt.Sprintf("%s.amount", t)
}

func (t tableTransaction) ColumnIsIgnored() string {
	return fmt.Sprintf("%s.is_ignored", t)
}

func (t tableTransaction) ColumnCreatedAt() string {
	return fmt.Sprintf("%s.created_at", t)
}

func (t tableTransaction) ColumnUpdatedAt() string {
	return fmt.Sprintf("%s.updated_at", t)
}

func (t tableTransaction) ColumnDeletedAt() string {
	return fmt.Sprintf("%s.deleted_at", t)
}

func (t tableTransaction) ColumnInstitutionID() string {
	return fmt.Sprintf("%s.institution_id", t)
}

const Transaction = tableTransaction("transactions")

type tableTransactionCategory string

func (t tableTransactionCategory) Table() string {
	return string(t)
}

func (t tableTransactionCategory) ColumnAll() string {
	return fmt.Sprintf("%s.*", t)
}

func (t tableTransactionCategory) ColumnID() string {
	return fmt.Sprintf("%s.id", t)
}

func (t tableTransactionCategory) ColumnExternalID() string {
	return fmt.Sprintf("%s.external_id", t)
}

func (t tableTransactionCategory) ColumnName() string {
	return fmt.Sprintf("%s.name", t)
}

func (t tableTransactionCategory) ColumnCreatedAt() string {
	return fmt.Sprintf("%s.created_at", t)
}

func (t tableTransactionCategory) ColumnUpdatedAt() string {
	return fmt.Sprintf("%s.updated_at", t)
}

func (t tableTransactionCategory) ColumnDeletedAt() string {
	return fmt.Sprintf("%s.deleted_at", t)
}

const TransactionCategory = tableTransactionCategory("transaction_categories")

type tableUser string

func (t tableUser) Table() string {
	return string(t)
}

func (t tableUser) ColumnAll() string {
	return fmt.Sprintf("%s.*", t)
}

func (t tableUser) ColumnSubscriptionExpiresAt() string {
	return fmt.Sprintf("%s.subscription_expires_at", t)
}

func (t tableUser) ColumnSynchronizedAt() string {
	return fmt.Sprintf("%s.synchronized_at", t)
}

func (t tableUser) ColumnCreatedAt() string {
	return fmt.Sprintf("%s.created_at", t)
}

func (t tableUser) ColumnTier() string {
	return fmt.Sprintf("%s.tier", t)
}

func (t tableUser) ColumnUpdatedAt() string {
	return fmt.Sprintf("%s.updated_at", t)
}

func (t tableUser) ColumnDeletedAt() string {
	return fmt.Sprintf("%s.deleted_at", t)
}

func (t tableUser) ColumnID() string {
	return fmt.Sprintf("%s.id", t)
}

func (t tableUser) ColumnName() string {
	return fmt.Sprintf("%s.name", t)
}

func (t tableUser) ColumnEmail() string {
	return fmt.Sprintf("%s.email", t)
}

func (t tableUser) ColumnAvatar() string {
	return fmt.Sprintf("%s.avatar", t)
}

const User = tableUser("users")

type tableUserAuthProvider string

func (t tableUserAuthProvider) Table() string {
	return string(t)
}

func (t tableUserAuthProvider) ColumnAll() string {
	return fmt.Sprintf("%s.*", t)
}

func (t tableUserAuthProvider) ColumnExternalID() string {
	return fmt.Sprintf("%s.external_id", t)
}

func (t tableUserAuthProvider) ColumnProvider() string {
	return fmt.Sprintf("%s.provider", t)
}

func (t tableUserAuthProvider) ColumnVerifiedEmail() string {
	return fmt.Sprintf("%s.verified_email", t)
}

func (t tableUserAuthProvider) ColumnCreatedAt() string {
	return fmt.Sprintf("%s.created_at", t)
}

func (t tableUserAuthProvider) ColumnUpdatedAt() string {
	return fmt.Sprintf("%s.updated_at", t)
}

func (t tableUserAuthProvider) ColumnDeletedAt() string {
	return fmt.Sprintf("%s.deleted_at", t)
}

func (t tableUserAuthProvider) ColumnUserID() string {
	return fmt.Sprintf("%s.user_id", t)
}

func (t tableUserAuthProvider) ColumnID() string {
	return fmt.Sprintf("%s.id", t)
}

const UserAuthProvider = tableUserAuthProvider("user_auth_providers")

type tableUserInstitution string

func (t tableUserInstitution) Table() string {
	return string(t)
}

func (t tableUserInstitution) ColumnAll() string {
	return fmt.Sprintf("%s.*", t)
}

func (t tableUserInstitution) ColumnInstitutionID() string {
	return fmt.Sprintf("%s.institution_id", t)
}

func (t tableUserInstitution) ColumnID() string {
	return fmt.Sprintf("%s.id", t)
}

func (t tableUserInstitution) ColumnExternalID() string {
	return fmt.Sprintf("%s.external_id", t)
}

func (t tableUserInstitution) ColumnCreatedAt() string {
	return fmt.Sprintf("%s.created_at", t)
}

func (t tableUserInstitution) ColumnDeletedAt() string {
	return fmt.Sprintf("%s.deleted_at", t)
}

func (t tableUserInstitution) ColumnUserID() string {
	return fmt.Sprintf("%s.user_id", t)
}

const UserInstitution = tableUserInstitution("user_institutions")
