// Code generated by prisma-to-go. DO NOT EDIT.

package query

type Table string

const (
	TableAccount        Table = "accounts"
	TableBudget         Table = "budgets"
	TableBudgetCategory Table = "budget_categories"
	TableCategory       Table = "categories"
	TableInstitution    Table = "institutions"
	TableInvestment     Table = "investments"
	TableTransaction    Table = "transactions"
	TableUser           Table = "users"
)

type Column string

// Columns for table Account
const (
	ColumnAccountCreatedAt     Column = "created_at"
	ColumnAccountDeletedAt     Column = "deleted_at"
	ColumnAccountExternalID    Column = "external_id"
	ColumnAccountID            Column = "id"
	ColumnAccountInstitutionID Column = "institution_id"
	ColumnAccountName          Column = "name"
	ColumnAccountType          Column = "type"
	ColumnAccountUpdatedAt     Column = "updated_at"
	ColumnAccountUserID        Column = "user_id"
)

// Columns for table Budget
const (
	ColumnBudgetAmount    Column = "amount"
	ColumnBudgetCreatedAt Column = "created_at"
	ColumnBudgetDate      Column = "date"
	ColumnBudgetDeletedAt Column = "deleted_at"
	ColumnBudgetID        Column = "id"
	ColumnBudgetUpdatedAt Column = "updated_at"
	ColumnBudgetUserID    Column = "user_id"
)

// Columns for table BudgetCategory
const (
	ColumnBudgetCategoryAmount     Column = "amount"
	ColumnBudgetCategoryBudgetID   Column = "budget_id"
	ColumnBudgetCategoryCategoryID Column = "category_id"
	ColumnBudgetCategoryCreatedAt  Column = "created_at"
	ColumnBudgetCategoryDeletedAt  Column = "deleted_at"
	ColumnBudgetCategoryID         Column = "id"
	ColumnBudgetCategoryUpdatedAt  Column = "updated_at"
)

// Columns for table Category
const (
	ColumnCategoryCreatedAt  Column = "created_at"
	ColumnCategoryDeletedAt  Column = "deleted_at"
	ColumnCategoryExternalID Column = "external_id"
	ColumnCategoryID         Column = "id"
	ColumnCategoryName       Column = "name"
	ColumnCategoryUpdatedAt  Column = "updated_at"
)

// Columns for table Institution
const (
	ColumnInstitutionCreatedAt  Column = "created_at"
	ColumnInstitutionDeletedAt  Column = "deleted_at"
	ColumnInstitutionExternalID Column = "external_id"
	ColumnInstitutionID         Column = "id"
	ColumnInstitutionLogo       Column = "logo"
	ColumnInstitutionName       Column = "name"
	ColumnInstitutionUpdatedAt  Column = "updated_at"
)

// Columns for table Investment
const (
	ColumnInvestmentAmount     Column = "amount"
	ColumnInvestmentCreatedAt  Column = "created_at"
	ColumnInvestmentDeletedAt  Column = "deleted_at"
	ColumnInvestmentExternalID Column = "external_id"
	ColumnInvestmentID         Column = "id"
	ColumnInvestmentName       Column = "name"
	ColumnInvestmentRate       Column = "rate"
	ColumnInvestmentRateType   Column = "rateType"
	ColumnInvestmentType       Column = "type"
	ColumnInvestmentUpdatedAt  Column = "updated_at"
	ColumnInvestmentUserID     Column = "user_id"
)

// Columns for table Transaction
const (
	ColumnTransactionAccountID     Column = "account_id"
	ColumnTransactionAmount        Column = "amount"
	ColumnTransactionCategoryID    Column = "category_id"
	ColumnTransactionCreatedAt     Column = "created_at"
	ColumnTransactionDate          Column = "date"
	ColumnTransactionDeletedAt     Column = "deleted_at"
	ColumnTransactionExternalID    Column = "external_id"
	ColumnTransactionID            Column = "id"
	ColumnTransactionInstitutionID Column = "institution_id"
	ColumnTransactionIsIgnored     Column = "is_ignored"
	ColumnTransactionName          Column = "name"
	ColumnTransactionPaymentMethod Column = "payment_method"
	ColumnTransactionUpdatedAt     Column = "updated_at"
	ColumnTransactionUserID        Column = "user_id"
)

// Columns for table User
const (
	ColumnUserAvatar                Column = "avatar"
	ColumnUserCreatedAt             Column = "created_at"
	ColumnUserDeletedAt             Column = "deleted_at"
	ColumnUserEmail                 Column = "email"
	ColumnUserExternalID            Column = "external_id"
	ColumnUserID                    Column = "id"
	ColumnUserName                  Column = "name"
	ColumnUserProvider              Column = "provider"
	ColumnUserSubscriptionExpiresAt Column = "subscription_expires_at"
	ColumnUserSynchronizedAt        Column = "synchronized_at"
	ColumnUserTier                  Column = "tier"
	ColumnUserUpdatedAt             Column = "updated_at"
	ColumnUserVerifiedEmail         Column = "verified_email"
)
