basePath: /api
definitions:
  dto.CompoundInterestRequestDTO:
    properties:
      initial_deposit:
        minimum: 0
        type: number
      interest:
        maximum: 100
        minimum: 0
        type: number
      interest_type:
        allOf:
        - $ref: '#/definitions/entity.InterestType'
        enum:
        - MONTHLY
        - ANNUAL
      monthly_deposit:
        type: number
      period_in_months:
        minimum: 1
        type: integer
    required:
    - interest
    - interest_type
    - period_in_months
    type: object
  dto.CompoundInterestResponseDTO:
    properties:
      by_month:
        additionalProperties:
          $ref: '#/definitions/usecase.CompoundInterestResult'
        type: object
      total_amount:
        type: number
      total_deposit:
        type: number
      total_interest:
        type: number
    type: object
  dto.EmergencyReserveRequestDTO:
    properties:
      jobType:
        allOf:
        - $ref: '#/definitions/entity.JobType'
        enum:
        - ENTREPRENEUR
        - EMPLOYEE
        - CIVIL_SERVANT
      monthlyExpenses:
        minimum: 0
        type: number
      monthlyIncome:
        minimum: 0
        type: number
      monthlySavingsPercentage:
        maximum: 100
        minimum: 0
        type: number
    required:
    - jobType
    type: object
  dto.EmergencyReserveResponseDTO:
    properties:
      monthsToAchieveEmergencyReserve:
        type: integer
      recommendedReserveInMonths:
        type: integer
      recommendedReserveInValue:
        type: number
    type: object
  dto.ErrorResponseDTO:
    properties:
      message:
        type: string
    type: object
  dto.HealthResponseDTO:
    properties:
      ok:
        type: boolean
    type: object
  dto.RetirementRequestDTO:
    properties:
      age:
        minimum: 0
        type: integer
      goal_income:
        minimum: 0
        type: number
      goal_patrimony:
        minimum: 0
        type: number
      income_investment_percentage:
        maximum: 100
        minimum: 0
        type: number
      initial_deposit:
        minimum: 0
        type: number
      interest:
        maximum: 100
        minimum: 0
        type: number
      interest_type:
        allOf:
        - $ref: '#/definitions/entity.InterestType'
        enum:
        - MONTHLY
        - ANNUAL
      life_expectancy:
        minimum: 1
        type: integer
      monthly_income:
        minimum: 0
        type: number
      retirement_age:
        minimum: 1
        type: integer
    required:
    - age
    - goal_income
    - goal_patrimony
    - income_investment_percentage
    - initial_deposit
    - interest
    - interest_type
    - monthly_income
    - retirement_age
    type: object
  dto.RetirementResponseDTO:
    properties:
      achieved_goal_income:
        type: boolean
      achieved_goal_patrimony:
        type: boolean
      heritage:
        type: number
      max_monthly_expenses:
        type: number
      property_on_retirement:
        type: number
    type: object
  dto.SignInRequestDTO:
    properties:
      provider:
        $ref: '#/definitions/entity.Provider'
    type: object
  dto.SignInResponseDTO:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
      user:
        $ref: '#/definitions/entity.User'
    type: object
  dto.SimpleInterestRequestDTO:
    properties:
      initialDeposit:
        minimum: 0
        type: number
      interest:
        maximum: 100
        minimum: 0
        type: number
      interestType:
        allOf:
        - $ref: '#/definitions/entity.InterestType'
        enum:
        - MONTHLY
        - ANNUAL
      periodInMonths:
        minimum: 1
        type: integer
    required:
    - interest
    - interestType
    - periodInMonths
    type: object
  dto.SimpleInterestResponseDTO:
    properties:
      by_month:
        additionalProperties:
          $ref: '#/definitions/usecase.SimpleInterestResult'
        type: object
      total_amount:
        type: number
      total_deposit:
        type: number
      total_interest:
        type: number
    type: object
  entity.InterestType:
    enum:
    - MONTHLY
    - ANNUAL
    type: string
    x-enum-varnames:
    - InterestTypeMonthly
    - InterestTypeAnnual
  entity.JobType:
    enum:
    - ENTREPRENEUR
    - EMPLOYEE
    - CIVIL_SERVANT
    type: string
    x-enum-varnames:
    - JobTypeEntrepreneur
    - JobTypeEmployee
    - JobTypeCivilServant
  entity.Provider:
    enum:
    - GOOGLE
    - APPLE
    - REFRESH
    - MOCK
    type: string
    x-enum-varnames:
    - ProviderGoogle
    - ProviderApple
    - ProviderRefresh
    - ProviderMock
  entity.User:
    properties:
      avatar:
        type: string
      created_at:
        type: string
      email:
        type: string
      external_id:
        type: string
      id:
        type: string
      name:
        type: string
      provider:
        type: string
      subscription_expires_at:
        type: string
      synchronized_at:
        type: string
      tier:
        type: string
      updated_at:
        type: string
      verified_email:
        type: boolean
    type: object
  usecase.CompoundInterestResult:
    properties:
      monthly_interest:
        type: number
      total_amount:
        type: number
      total_deposit:
        type: number
      total_interest:
        type: number
    type: object
  usecase.SimpleInterestResult:
    properties:
      total_amount:
        type: number
      total_deposit:
        type: number
      total_interest:
        type: number
    type: object
info:
  contact:
    email: danielmesquitta123@gmail.com
    name: Daniel Mesquita
  description: API Finance Manager
  title: API Finance Manager
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Health check
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.HealthResponseDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
      summary: Health check
      tags:
      - Health
  /v1/admin/institutions/sync:
    get:
      consumes:
      - application/json
      description: Sync institutions from open finance
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
      security:
      - BasicAuth: []
      summary: Sync institutions from open finance
      tags:
      - Institution
  /v1/auth/refresh:
    post:
      consumes:
      - application/json
      description: Use refresh token to generate new access token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SignInResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
      security:
      - BearerAuth: []
      summary: Refresh token
      tags:
      - Auth
  /v1/auth/sign-in:
    post:
      consumes:
      - application/json
      description: Authenticate user through Google or Apple token
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.SignInRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SignInResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
      security:
      - BearerAuth: []
      summary: Sign in
      tags:
      - Auth
  /v1/calculator/compound-interest:
    post:
      consumes:
      - application/json
      description: Calculate compound interest
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CompoundInterestRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CompoundInterestResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
      security:
      - BearerAuth: []
      summary: Calculate compound interest
      tags:
      - Calculator
  /v1/calculator/emergency-reserve:
    post:
      consumes:
      - application/json
      description: Calculate emergency reserve
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.EmergencyReserveRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.EmergencyReserveResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
      security:
      - BearerAuth: []
      summary: Calculate emergency reserve
      tags:
      - Calculator
  /v1/calculator/retirement:
    post:
      consumes:
      - application/json
      description: Calculate investments needed for retirement
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.RetirementRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.RetirementResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
      security:
      - BearerAuth: []
      summary: Calculate retirement
      tags:
      - Calculator
  /v1/calculator/simple-interest:
    post:
      consumes:
      - application/json
      description: Calculate simple interest
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.SimpleInterestRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SimpleInterestResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponseDTO'
      security:
      - BearerAuth: []
      summary: Calculate simple interest
      tags:
      - Calculator
securityDefinitions:
  BasicAuth:
    type: basic
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
